In [1]:
import geopandas as gpd

In [2]:
df_links = gpd.read_file("PJT001_moc_link_2018.geojson")

In [3]:
df_links.shape

(10563, 27)

In [4]:
df_links.head()

,id,link_id,f_node,t_node,road_use,lanes,road_rank,road_name,multi_link,connect,...,dept_code,stnl_reg,road_type,road_no,tmpid,upload_id,sosfnodeid,sostnodeid,shape_stle,geometry
0,63255,2333070000,2330045500,2330045200,0,1.0,107,-,0,000,...,41590,233,000,-,NTIC_0616 U,None,TEMP1074,TEMP1073,154.657772,"MULTILINESTRING ((126.81451 37.14096, 126.8155..."
1,63119,2330018207,2330007302,2330007304,0,2.0,103,일반국도43호선,0,000,...,41590,233,000,43,None,None,None,None,235.832927,"MULTILINESTRING ((126.91828 37.14319, 126.9186..."
2,63120,2330018108,2330007305,2330007304,0,2.0,103,일반국도43호선,0,000,...,41590,233,000,43,None,None,None,None,77.012754,"MULTILINESTRING ((126.91982 37.14574, 126.9197..."
3,63150,2333144900,2330079100,2330076000,0,2.0,107,-,0,000,...,41590,233,000,-,None,None,TEMP846,TEMP636,368.373468,"MULTILINESTRING ((127.04169 37.20703, 127.0417..."
4,63176,2230004902,2330009100,2330009101,0,1.0,106,지방도314호선,0,000,...,41590,233,000,314,None,None,None,None,2351.958941,"MULTILINESTRING ((127.00177 37.16565, 127.0017..."

In [6]:
# 중복 제거
df_links.drop_duplicates(subset=['f_node', 't_node'], inplace=True)

# 잘못된 노드정보 보정
df_links.loc[5636, 't_node'] = 'temp1'
df_links.loc[5638, 'f_node'] = 'temp1'
df_links.loc[[7075, 7079, 7086], 'f_node'] = 'temp2'
df_links.loc[[7082, 7085, 7087], 't_node'] = 'temp2'
df_links.loc[[7076, 7084, 7085], 'f_node'] = 'temp3'
df_links.loc[[7078, 7081, 7086], 't_node'] = 'temp3'

In [7]:
df_links.to_file('gis/제공된도로링크.shp')